version: '3.8'

services:
  backend:
    build: ./app
    container_name: tss_site_backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@tssvpn-db:5432/${POSTGRES_DB}
      MARZBAN_URL: ${MARZBAN_URL}
      MARZBAN_USERNAME: ${MARZBAN_USERNAME}
      MARZBAN_PASSWORD: ${MARZBAN_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - tssvpn-network

  frontend_next:
    build: ./frontend_next
    container_name: tss_site_frontend_next
    restart: always
    command: npm run dev
    volumes:
      - ./frontend_next:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BOT_USERNAME=${NEXT_PUBLIC_BOT_USERNAME}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - tssvpn-network

  nginx:
    image: nginx:alpine
    container_name: tss_site_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend_next
    networks:
      - tssvpn-network

networks:
  tssvpn-network:
    external: true